export interface MenuItem {
  name: string;
}

export interface MenuCategory {
  id: string;
  label: string;
  items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: "01-drinks",
    label: "Drinks",
    items: [
      { name: "Hot Chocolate" },
      { name: "Pepsi" },
      { name: "Mineral Water S" },
      { name: "Diet Pepsi" },
      { name: "Fresh Lime Soda" },
      { name: "Mineral Water L" },
      { name: "Cappuccino" },
      { name: "7UP" },
      { name: "Smoked Pineapple Limeade" },
      { name: "Spanish Latte" },
      { name: "Berry And Pomegranate Fizz" },
      { name: "Fresh Juice" },
      { name: "Diet 7UP" },
      { name: "Pomegranate Berry Spritzer" },
      { name: "Latte" },
      { name: "Matcha With Cold Foam" },
      { name: "Iced Latte" },
      { name: "Fresh Lime Soft Drink" },
      { name: "Earl Grey Iced Tea W Yuzu Foam" },
      { name: "Green Tea" },
      { name: "Black Tea" },
      { name: "Thai Milk Iced Tea" },
      { name: "Americano" },
      { name: "Tokyo Jelly Iced Latte" },
      { name: "Espresso" },
      { name: "Sakura Lychee Matcha" },
      { name: "Mirinda" },
      { name: "Kyoto Cloud" },
      { name: "Flavoured Cappucino/Latte" },
      { name: "Matcha Latte" },
      { name: "Iced Matcha" },
      { name: "Blooming Tea" },
      { name: "Iced Americano" },
      { name: "Matcha With Strawberry Cold Foam" },
      { name: "Matcha Vanilla Latte" },
      { name: "Mocca Latte" },
      { name: "Cappucino (Regular/Skinny)" },
      { name: "Lemon Mint Ice Tea" },
      { name: "Peach Iced Tea" },
      { name: "Vietnamese Ice Coffee" },
    ],
  },
  {
    id: "02-soups-salads",
    label: "Soups + Salads",
    items: [
      { name: "Furikake French Fries" },
      { name: "Katsu Chicken Caesar" },
      { name: "Korean Cream Cheese Bun" },
      { name: "Miso Soup" },
      { name: "Mushroom And Truffle Soup" },
      { name: "Thai Beef Salad" },
      { name: "Wakame Salad" },
      { name: "Wonton Soup" },
    ],
  },
  {
    id: "03-small-plates",
    label: "Small Plates",
    items: [
      { name: "5 Spice Chicken" },
      { name: "Fried Okra" },
      { name: "Korean Fried Chicken" },
      { name: "Korean Popcorn Chicken" },
      { name: "Miso Cabbage" },
      { name: "Prawn Toast" },
      { name: "Rock Shrimp Tempura" },
      { name: "Sticky Chicken Wings" },
      { name: "Taquitos One Of Each" },
      { name: "Taquitos Prawn" },
      { name: "Taquitos Salmon" },
      { name: "Taquitos Tuna" },
    ],
  },
  {
    id: "04-sushi-classic-maki",
    label: "Sushi Classic Maki",
    items: [
      { name: "California Roll" },
      { name: "California Sunset" },
      { name: "Crunchy Maki" },
      { name: "Spicy Salmon" },
      { name: "Spicy Tuna" },
      { name: "Volcano Maki" },
    ],
  },
  {
    id: "05-como-special-maki",
    label: "Como Special Maki",
    items: [
      { name: "Dynamite Crunchy Maki" },
      { name: "Paola Rainbow" },
      { name: "Salmon Avocado" },
      { name: "Sushi Tower" },
      { name: "The Dragon" },
      { name: "The Royal" },
      { name: "The Spicy Spider" },
      { name: "Truffled Beef Aburi" },
      { name: "Volcano Maki" },
    ],
  },
  {
    id: "06-nigiri-sashimi",
    label: "Nigiri + Sashimi",
    items: [
      { name: "Nigiri Crabstick" },
      { name: "Nigiri Eel" },
      { name: "Nigiri Prawn" },
      { name: "Nigiri Salmon" },
      { name: "Nigiri Sashimi" },
      { name: "Nigiri Tuna" },
      { name: "Nigiri Selection" },
      { name: "Sashimi Salmon" },
      { name: "Sashimi Tuna" },
      { name: "Special Salmon Nigiri" },
      { name: "Special Tuna Nigiri" },
    ],
  },
  {
    id: "07-sushi-platter",
    label: "Sushi Platter",
    items: [
      { name: "Classic Maki Selection Full" },
      { name: "Classic Maki Selection Half" },
      { name: "Mini Paola Special" },
      { name: "Special Selection" },
      { name: "Strawberry Granola Bowl" },
    ],
  },
  {
    id: "08-bao-buns",
    label: "Bao Buns",
    items: [
      { name: "Bao Buns One Of Each" },
      { name: "Smoky Beef Bao Bun" },
      { name: "Teriyaki Chicken Bao Bun" },
      { name: "Tofu Bao Bun" },
      { name: "Tofu Tempura" },
    ],
  },
  {
    id: "09-dim-sum",
    label: "Dim Sum",
    items: [
      { name: "Crispy Skirt Gyozas" },
      { name: "Mushroom Truffle Dumplings" },
      { name: "Prawn And Herb Dumplings" },
      { name: "Wontons In Spicy Soy" },
    ],
  },
  {
    id: "10-gourmet-selection",
    label: "Gourmet Selection",
    items: [
      { name: "Agedashi Tofu" },
      { name: "Aus Beef Carpaccio" },
      { name: "Charred Chicken" },
      { name: "Chili Tomato Burrata" },
      { name: "Classic Prawn Tempura" },
      { name: "Salmon Carpaccio" },
      { name: "Salmon Crudo" },
      { name: "Salmon With Miso Glaze" },
      { name: "Steak Frite" },
      { name: "Tuna Tostada" },
      { name: "Valentine Menu" },
      { name: "Valentine Special Menu" },
      { name: "Wagyu Steak" },
    ],
  },
  {
    id: "11-specialty-sandwiches",
    label: "Specialty Sandwiches",
    items: [
      { name: "Beef Burger With Chili Crisps" },
      { name: "Fish Tempura Burger" },
      { name: "Mushroom And Truffle Burger" },
      { name: "Prawn Roll" },
    ],
  },
  {
    id: "12-paola-special-seared",
    label: "Paola Special Seared",
    items: [
      { name: "Seared Salmon" },
      { name: "Seared Tuna" },
    ],
  },
  {
    id: "13-noodles-rice",
    label: "Noodles & Rice",
    items: [
      { name: "Beef Fried Rice" },
      { name: "Chicken Fried Rice" },
      { name: "Fatima's Laksa" },
      { name: "Kimchi & Cheese Fried Rice" },
      { name: "Lo Mein" },
      { name: "Prawn Fried Rice" },
      { name: "Tan Tan Ramen" },
      { name: "Veg Lo Mein" },
    ],
  },
  {
    id: "14-the-classics",
    label: "The Classics",
    items: [
      { name: "Beef Bulgogi" },
      { name: "Beef Chili Dry" },
      { name: "Katsu Curry" },
      { name: "Szechuan Chicken" },
      { name: "Tamarind Fish" },
      { name: "Thai Style Cashew Chicken" },
      { name: "Typhoon Shelter Shrimp" },
    ],
  },
  {
    id: "15-teppanyaki",
    label: "Teppanyaki",
    items: [
      { name: "Teppanyaki Angus Ribeye" },
      { name: "Teppanyaki Beef" },
      { name: "Teppanyaki Chicken" },
      { name: "Teppanyaki Lamb Chops" },
      { name: "Teppanyaki Lobster" },
      { name: "Teppanyaki Prawn" },
      { name: "Teppanyaki Salmon" },
      { name: "Teppanyaki Sole" },
      { name: "Teppanyaki Wagyu" },
    ],
  },
  {
    id: "16-sides",
    label: "Sides",
    items: [
      { name: "Asian Mash" },
      { name: "Bok Choy In Oyster" },
      { name: "Chili Garlic French Beans" },
      { name: "Garlic Rice" },
      { name: "Hand-Cut French Fries" },
      { name: "House-Made Fermented Chili Sauce" },
      { name: "Kimchi" },
      { name: "Miso Onion" },
      { name: "Sticky Rice" },
      { name: "Stir Fried Veg" },
    ],
  },
  {
    id: "17-como-dessert",
    label: "Como Dessert",
    items: [
      { name: "Apple And Pear Crumble" },
      { name: "Apple Crumble" },
      { name: "Cookie Bento" },
      { name: "Matcha Single Scoop" },
      { name: "Molten Chocolate Cake" },
      { name: "Vanilla Single Scoop" },
    ],
  },
  {
    id: "breads-etc",
    label: "Breads Etc",
    items: [
      { name: "Blueberry Ricotta Toast" },
      { name: "Granola Bowl" },
      { name: "Sourdough & Butter Selection" },
    ],
  },
  {
    id: "dessert",
    label: "Dessert",
    items: [
      { name: "Chocolate Mochi Dumplings" },
      { name: "Gelato Selection" },
      { name: "Mini Smores Set" },
      { name: "Smores Set" },
      { name: "Yuzu Panacotta" },
    ],
  },
  {
    id: "main-plates-sandos",
    label: "Main Plates & Sandos",
    items: [
      { name: "Beef Chili Crisp Burger" },
      { name: "Fish Tempura Burger Brunch" },
      { name: "Korean Fried Chicken Sando" },
      { name: "Steak & Eggs" },
      { name: "Zhendang / Steamed Eggs" },
    ],
  },
  {
    id: "okonomiyaki",
    label: "Okonomiyaki",
    items: [
      { name: "Beef Bulgogi Brunch" },
      { name: "Chicken Floss" },
      { name: "Miso Prawn" },
      { name: "Tofu Tempura Brunch" },
    ],
  },
  {
    id: "pm-soups",
    label: "PM Soups",
    items: [
      { name: "Beef Chilli Stir Fry" },
      { name: "Chocolate Cake Molten" },
      { name: "Lo Mein D" },
      { name: "Pear & Apple Crumble" },
    ],
  },
  {
    id: "sharing-snacks-salads",
    label: "Sharing Snacks & Salads",
    items: [
      { name: "Beef Bulgogi Tacos" },
      { name: "Breakfast Baos" },
      { name: "Bulgogi Tacos" },
      { name: "Donut Holes" },
    ],
  },
  {
    id: "snack-bar",
    label: "Snack Bar",
    items: [
      { name: "French Fries" },
      { name: "Spring Rolls With Sweet Chili Sauce" },
    ],
  },
  {
    id: "sweet-endings",
    label: "Sweet Endings",
    items: [
      { name: "Cereal Panna Cotta" },
      { name: "Matcha Berry French Toast" },
      { name: "Miso Banana Bread" },
      { name: "Ricotta Pancakes" },
    ],
  },
  {
    id: "tartines-eggs",
    label: "Tartines & Eggs",
    items: [
      { name: "Avocado + Tobiko" },
      { name: "Miso Mushroom" },
      { name: "Miso Mushroom + Ricotta" },
      { name: "Tomato + Burrata" },
    ],
  },
];
